
package com.anonymous.solar.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LocationInformation", targetNamespace = "http://server.solar.anonymous.com/")
@XmlSeeAlso({
    LocationObjectFactory.class
})
public interface LocationInformation {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "StoreLocationInformation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "StoreLocationInformation", targetNamespace = "http://server.solar.anonymous.com/", className = "com.anonymous.solar.client.StoreLocationInformation")
    @ResponseWrapper(localName = "StoreLocationInformationResponse", targetNamespace = "http://server.solar.anonymous.com/", className = "com.anonymous.solar.client.StoreLocationInformationResponse")
    public Long storeLocationInformation(
        @WebParam(name = "arg0", targetNamespace = "")
        LocationData arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.anonymous.solar.client.LocationData>
     */
    @WebMethod(operationName = "StoreLocationGetAll")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "StoreLocationGetAll", targetNamespace = "http://server.solar.anonymous.com/", className = "com.anonymous.solar.client.StoreLocationGetAll")
    @ResponseWrapper(localName = "StoreLocationGetAllResponse", targetNamespace = "http://server.solar.anonymous.com/", className = "com.anonymous.solar.client.StoreLocationGetAllResponse")
    public List<LocationData> storeLocationGetAll();

}
