
package com.anonymous.solar.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LocationInformationService", targetNamespace = "http://server.solar.anonymous.com/", wsdlLocation = "http://anonymous-solarenergy.appspot.com/LocationInformationService.wsdl")
public class LocationInformationService
    extends Service
{

    private final static URL LOCATIONINFORMATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.anonymous.solar.client.LocationInformationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.anonymous.solar.client.LocationInformationService.class.getResource(".");
            url = new URL(baseUrl, "http://anonymous-solarenergy.appspot.com/LocationInformationService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://anonymous-solarenergy.appspot.com/LocationInformationService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOCATIONINFORMATIONSERVICE_WSDL_LOCATION = url;
    }

    public LocationInformationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationInformationService() {
        super(LOCATIONINFORMATIONSERVICE_WSDL_LOCATION, new QName("http://server.solar.anonymous.com/", "LocationInformationService"));
    }

    /**
     * 
     * @return
     *     returns LocationInformation
     */
    @WebEndpoint(name = "LocationInformationPort")
    public LocationInformation getLocationInformationPort() {
        return super.getPort(new QName("http://server.solar.anonymous.com/", "LocationInformationPort"), LocationInformation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocationInformation
     */
    @WebEndpoint(name = "LocationInformationPort")
    public LocationInformation getLocationInformationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.solar.anonymous.com/", "LocationInformationPort"), LocationInformation.class, features);
    }

}
