
package com.anonymous.solar.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.anonymous.solar.shared.SolarPanel;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SPanel", targetNamespace = "http://server.solar.anonymous.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SPanel {


    /**
     * 
     * @return
     *     returns java.util.List<com.anonymous.solar.client.SolarPanel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPanels", targetNamespace = "http://server.solar.anonymous.com/", className = "com.anonymous.solar.client.GetPanels")
    @ResponseWrapper(localName = "getPanelsResponse", targetNamespace = "http://server.solar.anonymous.com/", className = "com.anonymous.solar.client.GetPanelsResponse")
    public List<SolarPanel> getPanels();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPanel", targetNamespace = "http://server.solar.anonymous.com/", className = "com.anonymous.solar.client.InsertPanel")
    @ResponseWrapper(localName = "insertPanelResponse", targetNamespace = "http://server.solar.anonymous.com/", className = "com.anonymous.solar.client.InsertPanelResponse")
    public boolean insertPanel(
        @WebParam(name = "arg0", targetNamespace = "")
        SolarPanel arg0);

}
