/**
 * 
 */
package com.anonymous.solar.desktop;

/**
 * Information Entry Panel for Desktop Application
 * 
 * @author 07627505 Darran Kartaschew
 * @version 1.0
 */
public class InformationEntryJPanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3321276319902514732L;
	/**
     * Creates new form InformationEntryJPanel
     */
    public InformationEntryJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDetailsGroup = new javax.swing.JPanel();
        jLabelSetupName = new javax.swing.JLabel();
        jTextFieldSetupName = new javax.swing.JTextField();
        jLabelSetupDescription = new javax.swing.JLabel();
        jScrollPaneSetupDescription = new javax.swing.JScrollPane();
        jTextAreaSetupDescription = new javax.swing.JTextArea();
        jLabelLocation = new javax.swing.JLabel();
        jTextFieldLocation = new javax.swing.JTextField();
        jButtonSetLocation = new javax.swing.JButton();
        jPanelElectricalGroup = new javax.swing.JPanel();
        jLabelInverter = new javax.swing.JLabel();
        jTextFieldInverter = new javax.swing.JTextField();
        jButtonSetInverter = new javax.swing.JButton();
        jLabelWiringLength = new javax.swing.JLabel();
        jTextFieldWiringLength = new javax.swing.JTextField();
        jLabelWiringEfficiency = new javax.swing.JLabel();
        jTextFieldWiringEfficiency = new javax.swing.JTextField();
        jPanelPanelInformationGroup = new javax.swing.JPanel();
        jScrollPaneSolarPanels = new javax.swing.JScrollPane();
        jTableSolarPanels = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();

        jPanelDetailsGroup.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));
        jPanelDetailsGroup.setName("Details"); // NOI18N

        jLabelSetupName.setText("Setup Name:");

        jLabelSetupDescription.setText("Setup Description:");

        jTextAreaSetupDescription.setColumns(20);
        jTextAreaSetupDescription.setRows(5);
        jScrollPaneSetupDescription.setViewportView(jTextAreaSetupDescription);

        jLabelLocation.setText("Location:");

        jTextFieldLocation.setEditable(false);

        jButtonSetLocation.setText("...");

        javax.swing.GroupLayout jPanelDetailsGroupLayout = new javax.swing.GroupLayout(jPanelDetailsGroup);
        jPanelDetailsGroup.setLayout(jPanelDetailsGroupLayout);
        jPanelDetailsGroupLayout.setHorizontalGroup(
            jPanelDetailsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailsGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSetupName)
                    .addComponent(jLabelLocation)
                    .addComponent(jLabelSetupDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSetupName)
                    .addComponent(jScrollPaneSetupDescription)
                    .addGroup(jPanelDetailsGroupLayout.createSequentialGroup()
                        .addComponent(jTextFieldLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSetLocation)))
                .addContainerGap())
        );
        jPanelDetailsGroupLayout.setVerticalGroup(
            jPanelDetailsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailsGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetupName)
                    .addComponent(jTextFieldSetupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDetailsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneSetupDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSetupDescription))
                .addGap(18, 18, 18)
                .addGroup(jPanelDetailsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetailsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelLocation))
                    .addComponent(jButtonSetLocation))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanelElectricalGroup.setBorder(javax.swing.BorderFactory.createTitledBorder("Electrical Components"));

        jLabelInverter.setText("Inverter:");

        jButtonSetInverter.setText("...");

        jLabelWiringLength.setText("Wiring Length:");

        jLabelWiringEfficiency.setText("Wiring Efficiency:");
        jLabelWiringEfficiency.setToolTipText("");

        javax.swing.GroupLayout jPanelElectricalGroupLayout = new javax.swing.GroupLayout(jPanelElectricalGroup);
        jPanelElectricalGroup.setLayout(jPanelElectricalGroupLayout);
        jPanelElectricalGroupLayout.setHorizontalGroup(
            jPanelElectricalGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelElectricalGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelElectricalGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInverter)
                    .addComponent(jLabelWiringLength))
                .addGap(38, 38, 38)
                .addGroup(jPanelElectricalGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelElectricalGroupLayout.createSequentialGroup()
                        .addComponent(jTextFieldInverter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSetInverter))
                    .addGroup(jPanelElectricalGroupLayout.createSequentialGroup()
                        .addComponent(jTextFieldWiringLength)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelWiringEfficiency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldWiringEfficiency)))
                .addContainerGap())
        );
        jPanelElectricalGroupLayout.setVerticalGroup(
            jPanelElectricalGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelElectricalGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelElectricalGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInverter)
                    .addComponent(jTextFieldInverter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSetInverter))
                .addGap(18, 18, 18)
                .addGroup(jPanelElectricalGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWiringLength)
                    .addComponent(jTextFieldWiringLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWiringEfficiency)
                    .addComponent(jTextFieldWiringEfficiency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelPanelInformationGroup.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Information"));

        jTableSolarPanels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneSolarPanels.setViewportView(jTableSolarPanels);

        jButtonAdd.setText("Add");

        javax.swing.GroupLayout jPanelPanelInformationGroupLayout = new javax.swing.GroupLayout(jPanelPanelInformationGroup);
        jPanelPanelInformationGroup.setLayout(jPanelPanelInformationGroupLayout);
        jPanelPanelInformationGroupLayout.setHorizontalGroup(
            jPanelPanelInformationGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanelInformationGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPanelInformationGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneSolarPanels, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPanelInformationGroupLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAdd)))
                .addContainerGap())
        );
        jPanelPanelInformationGroupLayout.setVerticalGroup(
            jPanelPanelInformationGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanelInformationGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneSolarPanels, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAdd)
                .addContainerGap())
        );

        jButtonCalculate.setText("Calculate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPanelInformationGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDetailsGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelElectricalGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCalculate)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDetailsGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelElectricalGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPanelInformationGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCalculate)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonSetInverter;
    private javax.swing.JButton jButtonSetLocation;
    private javax.swing.JLabel jLabelInverter;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelSetupDescription;
    private javax.swing.JLabel jLabelSetupName;
    private javax.swing.JLabel jLabelWiringEfficiency;
    private javax.swing.JLabel jLabelWiringLength;
    private javax.swing.JPanel jPanelDetailsGroup;
    private javax.swing.JPanel jPanelElectricalGroup;
    private javax.swing.JPanel jPanelPanelInformationGroup;
    private javax.swing.JScrollPane jScrollPaneSetupDescription;
    private javax.swing.JScrollPane jScrollPaneSolarPanels;
    private javax.swing.JTable jTableSolarPanels;
    private javax.swing.JTextArea jTextAreaSetupDescription;
    private javax.swing.JTextField jTextFieldInverter;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldSetupName;
    private javax.swing.JTextField jTextFieldWiringEfficiency;
    private javax.swing.JTextField jTextFieldWiringLength;
    // End of variables declaration//GEN-END:variables
}
