/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anonymous.solar.desktop;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JList;

import com.anonymous.solar.client.*;
import com.anonymous.solar.comparison.*;
import com.anonymous.solar.shared.TariffRate;

/**
 *
 * @author Thura
 */
public class LoadTariff extends javax.swing.JDialog {

    /**
     * Creates new form LoadPanel
     */
	WizardUserCosts parent;
	
    public LoadTariff(WizardUserCosts parent) {
        super(new JDialog(), true);
        initComponents();
        nameComponents();
        LoadStoredTariffs(new TariffStateComparer());
        this.parent = parent;
        btnLoadTariff.setEnabled(false);
    }
    
    /**
     * Load panels from the datastore
     * 
     * @param comparison - A comparator used to order the panels
     */
    private void LoadStoredTariffs(Comparator comparison){
    	TRate TRateSOAP = new TRateService().getTRatePort();
    	
		int counter = 0;
    	
        List<TariffRate> tRateData = (List<TariffRate>) TRateSOAP.getTariffRates();
        Collections.sort(tRateData, comparison);
        
        final Object[] objs = new Object[tRateData.size()];
        
        for (TariffRate tar : tRateData) {
                objs[counter] = tar;
                counter++;
        }
        
        
        lstPanelInformation.setModel(new javax.swing.AbstractListModel() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return objs.length; }
            public Object getElementAt(int i) { return objs[i]; }
        });
        
    }
    
    private void LoadStoredTariffs(String selected) {
    	TRate TRateSOAP = new TRateService().getTRatePort();
    	
        List<TariffRate> tRateData = (List<TariffRate>) TRateSOAP.getTariffRates();
        
        final List<Object> objs = new ArrayList<Object>();
        
        for (TariffRate tar : tRateData) {
        		if(tar.getTariffState().compareTo(selected) == 0){
        			objs.add(tar);
        		}
        }
        
		lstPanelInformation.setModel(new javax.swing.AbstractListModel() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return objs.size(); }
            public Object getElementAt(int i) { return objs.get(i); }
        });
		
	}

    public void nameComponents(){
    	lstPanelInformation.setName("lstTariffInformation");
    	txtTariffProvider.setName("txtTariffProvider");
        txtTariffState.setName("txtTariffState");
        txtTariffFeedIn.setName("txtTariffFeedIn");
        txtTariff11C.setName("txtTariff11C");
        txtTariff11F.setName("txtTariff11F");
        txtTariff33F.setName("txtTariff33F");
        txtTariff33C.setName("txtTariff33C");
    	btnLoadTariff.setName("btnLoadTariff");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cmbSortBy = new javax.swing.JComboBox();
        btnLoadTariff = new javax.swing.JButton();
        lblTariffProvider = new javax.swing.JLabel();
        lblTariffState = new javax.swing.JLabel();
        lblTariffFeedIn = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPanelInformation = new javax.swing.JList();
        lblTariff11C = new javax.swing.JLabel();
        lblTariff11F = new javax.swing.JLabel();
        txtTariffProvider = new javax.swing.JTextField();
        txtTariffState = new javax.swing.JTextField();
        txtTariffFeedIn = new javax.swing.JTextField();
        txtTariff11C = new javax.swing.JTextField();
        txtTariff11F = new javax.swing.JTextField();
        txtTariff33F = new javax.swing.JTextField();
        txtTariff33C = new javax.swing.JTextField();
        lblTariff33C = new javax.swing.JLabel();
        lblTariff33F = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lblSortBy = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        cmbSortBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "QLD", "NSW", "VIC", "TAS", "ACT", "NT", "SA", "WA" }));
        cmbSortBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSortByActionPerformed(evt);
            }
        });

        btnLoadTariff.setText("Load Tariff Rate");
        btnLoadTariff.setFocusCycleRoot(true);
        btnLoadTariff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadTariffActionPerformed(evt);
            }
        });

        lblTariffProvider.setText("Provider: ");
        lblTariffProvider.setToolTipText("");

        lblTariffState.setText("State: ");
        lblTariffState.setToolTipText("");

        lblTariffFeedIn.setText("Feed In Return: ");
        lblTariffFeedIn.setToolTipText("Cents per kWh pumped into the system");

        lstPanelInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstPanelInformationMouseReleased(evt);
            }
        });
        lstPanelInformation.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPanelInformationValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPanelInformation);

        lblTariff11C.setText("Tariff 11 Cost: ");

        lblTariff11F.setText("Tariff 11 Fee: ");

        txtTariffProvider.setEditable(false);
        txtTariffProvider.setToolTipText("Company that provides the power.");

        txtTariffState.setEditable(false);
        txtTariffState.setToolTipText("State you are located in");

        txtTariffFeedIn.setEditable(false);
        txtTariffFeedIn.setToolTipText("Cents per kWh pumped into the system");

        txtTariff11C.setEditable(false);
        txtTariff11C.setToolTipText("");

        txtTariff11F.setEditable(false);
        txtTariff11F.setToolTipText("");
        txtTariff11F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTariff11FActionPerformed(evt);
            }
        });

        txtTariff33F.setEditable(false);
        txtTariff33F.setToolTipText("");
        txtTariff33F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTariff33FActionPerformed(evt);
            }
        });

        txtTariff33C.setEditable(false);
        txtTariff33C.setToolTipText("");

        lblTariff33C.setText("Tariff 33 Cost:");

        lblTariff33F.setText("Tariff 33 Fee:");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblSortBy.setText("Select State: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTariffFeedIn)
                            .addComponent(lblTariffState)
                            .addComponent(lblTariffProvider))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTariffFeedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTariffProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTariffState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTariff11F)
                                    .addComponent(lblTariff11C))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTariff11F, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTariff11C, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 60, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTariff33C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTariff33F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTariff33C, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTariff33F, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLoadTariff, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblSortBy)
                        .addGap(12, 12, 12)
                        .addComponent(cmbSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSortBy)
                            .addComponent(cmbSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblTariffProvider)
                                            .addComponent(txtTariffProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblTariffState)
                                            .addComponent(txtTariffState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblTariff11C, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTariff11C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblTariff11F)
                                            .addComponent(txtTariff11F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTariffFeedIn)
                                    .addComponent(txtTariffFeedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTariff33C, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTariff33C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTariff33F, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTariff33F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnLoadTariff))
                        .addContainerGap())))
        );

        btnLoadTariff.getAccessibleContext().setAccessibleName("btnLoadPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Unused
     * @param evt
     */
    private void txtTariff11FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTariff11FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTariff11FActionPerformed
    /**
     * Unused
     * @param evt
     */
    private void txtTariff33FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTariff33FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTariff33FActionPerformed

    /**
     * Event handler to hanlde what happens when the sortBy combination box performs ANY action
     * @param evt
     */
    private void cmbSortByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSortByActionPerformed
        String selected = (String)cmbSortBy.getSelectedItem();
        
        LoadStoredTariffs(selected);
    }//GEN-LAST:event_cmbSortByActionPerformed
    

    

	/**
     * Event handler to handle what happens when the user tries to cancel the dialog
     * @param evt
     */
    private void btnLoadTariffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadTariffActionPerformed
        TariffRate trate = (TariffRate) lstPanelInformation.getSelectedValue();
        parent.LoadTariff(trate);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnLoadTariffActionPerformed

    /**
     * Event handler to handle what happens when the information value in the list box is changed
     * @param evt
     */
    private void lstPanelInformationValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPanelInformationValueChanged
    	TariffRate tariff = new TariffRate();
        tariff = (TariffRate)lstPanelInformation.getSelectedValue();
        
        if(tariff != null){
	        txtTariffProvider.setText(tariff.getTariffProvider());
	        txtTariffState.setText(tariff.getTariffState());
	        txtTariffFeedIn.setText(tariff.getTariffFeedInFee().toString());
	        txtTariff11F.setText(tariff.getTariff11Fee().toString());
	        txtTariff33C.setText(tariff.getTariff11Cost().toString());
	        txtTariff33F.setText(tariff.getTariff33Fee().toString());
	        txtTariff11C.setText(tariff.getTariff33Cost().toString());
    	}
    }//GEN-LAST:event_lstPanelInformationValueChanged

    /**
     * Event handler to handle what happens when the mouse is clicked on the list box
     * @param evt
     */
    private void lstPanelInformationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPanelInformationMouseReleased
        TariffRate tariff = new TariffRate();
        tariff = (TariffRate)lstPanelInformation.getSelectedValue();
        
        if(tariff != null){
	        txtTariffProvider.setText(tariff.getTariffProvider());
	        txtTariffState.setText(tariff.getTariffState());
	        txtTariffFeedIn.setText(tariff.getTariffFeedInFee().toString());
	        txtTariff11F.setText(tariff.getTariff11Fee().toString());
	        txtTariff33C.setText(tariff.getTariff11Cost().toString());
	        txtTariff33F.setText(tariff.getTariff33Fee().toString());
	        txtTariff11C.setText(tariff.getTariff33Cost().toString());
    	}
        btnLoadTariff.setEnabled(true);
    }//GEN-LAST:event_lstPanelInformationMouseReleased

    /**
     * Event handler to handle what happens when a user tries to cancel the dialog
     * @param evt
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLoadTariff;
    private javax.swing.JComboBox cmbSortBy;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSortBy;
    private javax.swing.JLabel lblTariff11C;
    private javax.swing.JLabel lblTariff11F;
    private javax.swing.JLabel lblTariff33C;
    private javax.swing.JLabel lblTariff33F;
    private javax.swing.JLabel lblTariffFeedIn;
    private javax.swing.JLabel lblTariffProvider;
    private javax.swing.JLabel lblTariffState;
    private javax.swing.JList lstPanelInformation;
    private javax.swing.JTextField txtTariff11C;
    private javax.swing.JTextField txtTariff11F;
    private javax.swing.JTextField txtTariff33C;
    private javax.swing.JTextField txtTariff33F;
    private javax.swing.JTextField txtTariffFeedIn;
    private javax.swing.JTextField txtTariffProvider;
    private javax.swing.JTextField txtTariffState;
    // End of variables declaration//GEN-END:variables
}
