/*
 *
 */
package com.anonymous.solar.desktop;

import javax.swing.JOptionPane;

import com.anonymous.solar.shared.SolarSetup;

/**
 * Main Entry Point for Desktop Application
 * 
 * @author 07627505 Darran Kartaschew
 * @version 1.0
 */
public class WizardSetupDescription extends javax.swing.JPanel implements WizardPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3202275394899767280L;
	private final String title = "Setup Description";
	private Wizard parent = null;

	/**
	 * Creates new form WizardFinish, with reference to parent
	 */
	public WizardSetupDescription(Wizard parent) {
		initComponents();
		this.parent = parent;
		// TODO: remove the following when we wish to deal with locations.
		jPanelLocationGroup.setVisible(false);
	}

	/**
	 * Creates new form WizardSetupDescription
	 */
	public WizardSetupDescription() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanelDetailsGroup = new javax.swing.JPanel();
		jLabelSetupName = new javax.swing.JLabel();
		jTextFieldSetupName = new javax.swing.JTextField();
		jLabelSetupDescription = new javax.swing.JLabel();
		jScrollPaneSetupDescription = new javax.swing.JScrollPane();
		jTextAreaSetupDescription = new javax.swing.JTextArea();
		jPanelLocationGroup = new javax.swing.JPanel();
		jLabelLocation1 = new javax.swing.JLabel();
		jTextFieldLocation1 = new javax.swing.JTextField();
		jButtonSetLocation1 = new javax.swing.JButton();
		jLabelLongHeader = new javax.swing.JLabel();
		jTextFieldLongitude = new javax.swing.JTextField();
		jLabelLatHeader = new javax.swing.JLabel();
		jTextFieldLatitude = new javax.swing.JTextField();

		jPanelDetailsGroup.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));
		jPanelDetailsGroup.setName("Details"); // NOI18N

		jLabelSetupName.setText("Setup Name:");

		jTextFieldSetupName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldSetupNameActionPerformed(evt);
			}
		});

		jLabelSetupDescription.setText("Setup Description:");

		jTextAreaSetupDescription.setColumns(20);
		jTextAreaSetupDescription.setRows(4);
		jScrollPaneSetupDescription.setViewportView(jTextAreaSetupDescription);

		javax.swing.GroupLayout jPanelDetailsGroupLayout = new javax.swing.GroupLayout(jPanelDetailsGroup);
		jPanelDetailsGroup.setLayout(jPanelDetailsGroupLayout);
		jPanelDetailsGroupLayout.setHorizontalGroup(jPanelDetailsGroupLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanelDetailsGroupLayout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								jPanelDetailsGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelSetupName).addComponent(jLabelSetupDescription))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanelDetailsGroupLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextFieldSetupName)
										.addComponent(jScrollPaneSetupDescription,
												javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
						.addContainerGap()));
		jPanelDetailsGroupLayout.setVerticalGroup(jPanelDetailsGroupLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanelDetailsGroupLayout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								jPanelDetailsGroupLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabelSetupName)
										.addComponent(jTextFieldSetupName, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(
								jPanelDetailsGroupLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPaneSetupDescription,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelSetupDescription)).addContainerGap(13, Short.MAX_VALUE)));

		jPanelLocationGroup.setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));

		jLabelLocation1.setText("Location:");

		jTextFieldLocation1.setEditable(false);

		jButtonSetLocation1.setText("...");

		jLabelLongHeader.setText("Longitude:");

		jTextFieldLongitude.setEditable(false);
		jTextFieldLongitude.setText("<longitude>");
		jTextFieldLongitude.setFocusable(false);

		jLabelLatHeader.setText("Latitude:");

		jTextFieldLatitude.setEditable(false);
		jTextFieldLatitude.setText("<latitude>");
		jTextFieldLatitude.setFocusable(false);

		javax.swing.GroupLayout jPanelLocationGroupLayout = new javax.swing.GroupLayout(jPanelLocationGroup);
		jPanelLocationGroup.setLayout(jPanelLocationGroupLayout);
		jPanelLocationGroupLayout.setHorizontalGroup(jPanelLocationGroupLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanelLocationGroupLayout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								jPanelLocationGroupLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelLongHeader).addComponent(jLabelLocation1))
						.addGap(33, 33, 33)
						.addGroup(
								jPanelLocationGroupLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanelLocationGroupLayout
														.createSequentialGroup()
														.addComponent(jTextFieldLocation1)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jButtonSetLocation1))
										.addGroup(
												jPanelLocationGroupLayout
														.createSequentialGroup()
														.addComponent(jTextFieldLongitude,
																javax.swing.GroupLayout.PREFERRED_SIZE, 160,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabelLatHeader)
														.addGap(18, 18, 18)
														.addComponent(jTextFieldLatitude,
																javax.swing.GroupLayout.PREFERRED_SIZE, 160,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		jPanelLocationGroupLayout.setVerticalGroup(jPanelLocationGroupLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanelLocationGroupLayout
								.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										jPanelLocationGroupLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														jPanelLocationGroupLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jTextFieldLocation1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabelLocation1))
												.addComponent(jButtonSetLocation1))
								.addGap(18, 18, 18)
								.addGroup(
										jPanelLocationGroupLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														jPanelLocationGroupLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabelLongHeader)
																.addComponent(jTextFieldLongitude,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														jPanelLocationGroupLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jTextFieldLatitude,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabelLatHeader)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jPanelDetailsGroup, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanelLocationGroup, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanelDetailsGroup, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanelLocationGroup, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(153, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void jTextFieldSetupNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldSetupNameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldSetupNameActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonSetLocation1;
	private javax.swing.JLabel jLabelLatHeader;
	private javax.swing.JLabel jLabelLocation1;
	private javax.swing.JLabel jLabelLongHeader;
	private javax.swing.JLabel jLabelSetupDescription;
	private javax.swing.JLabel jLabelSetupName;
	private javax.swing.JPanel jPanelDetailsGroup;
	private javax.swing.JPanel jPanelLocationGroup;
	private javax.swing.JScrollPane jScrollPaneSetupDescription;
	private javax.swing.JTextArea jTextAreaSetupDescription;
	private javax.swing.JTextField jTextFieldLatitude;
	private javax.swing.JTextField jTextFieldLocation1;
	private javax.swing.JTextField jTextFieldLongitude;
	private javax.swing.JTextField jTextFieldSetupName;

	// End of variables declaration//GEN-END:variables

	/**
	 * Callback method used by the parent panel to notify this panel that we
	 * have been given context to the user.
	 * 
	 * @return true is ok to move.
	 */
	@Override
	public boolean callbackStart() {
		SolarSetup global = parent.getSetup();
		if (global != null) {
			// Set to name and description fields.
			if (global.getSetupName() != null) {
				jTextFieldSetupName.setText(global.getSetupName());
			} else {
				jTextFieldSetupName.setText("");
			}
			if (global.getSetupDescription() != null) {
				jTextAreaSetupDescription.setText(global.getSetupDescription());
			} else {
				jTextAreaSetupDescription.setText("");
			}
		}
		return true;
	}

	/**
	 * Callback method used by the parent panel to notify this panel that we
	 * have requested a move away from this panel.
	 * 
	 * @return true is ok to move.
	 */
	@Override
	public boolean callbackDispose(boolean validateInput) {
		if (validateInput) {
			if ((jTextFieldSetupName.getText() == null) || (jTextFieldSetupName.getText().equals(""))) {
				// Oops, missing data, need to handle this.
				JOptionPane.showMessageDialog(this, "Please enter a setup name before continuing.",
						"Setup Name Missing", JOptionPane.OK_OPTION);
				return false;
			}
		}
		SolarSetup global = parent.getSetup();
		if (global != null) {
			// Store the name and description fields.
			global.setSetupName(jTextFieldSetupName.getText());
			global.setSetupDescription(jTextAreaSetupDescription.getText());
		}
		return true;
	}

	/**
	 * Return the title to be used for this wizard panel;
	 * 
	 * @return
	 */
	@Override
	public String getTitle() {
		return title;
	}
}
